project:
  type: website
  output-dir: docs

website:
  title: "ICON Research Group"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ICONgroupCWC/
      # - icon: twitter
      #   href: https://twitter.com
      - icon: linkedin
        href: https://www.linkedin.com/company/intelligent-connectivity-and-networks-group/
format:
  html:
    theme: cosmo
    css: styles.css



