---
title: "EuCNC 2024 Conference Paper"
author: "Rafaela Scaciota$^{1}$, Glauber Brante$^{2}$, Richard Souza$^{3}$, Onel Lopez$^{1}$, Septimia Sarbu$^{1}$, Mehdi Bennis$^{1}$, and Sumudu Samarakoon$^{1}$."
categories: [paper, conference, code]
toc: true
format:
  html:
    html-math-method: katex
    code-tools: false
    other-links:
      - text: Paper
        icon: file-earmark-pdf-fill
        href: https://arxiv.org/
      - text: Simulation Code
        icon: github
        href: https://github.com/rafaelascaciota/DecentralizedRL_EnergyEH.git
    self-contained: true
execute:
  warning: false
---

## Title
Decentralized RL-Based Data Transmission Scheme for Energy Efficient Harvesting

## Abstract

The evolving landscape of the Internet of Things (IoT) has given rise to a pressing need for an efficient communication scheme. As the IoT user ecosystem continues to expand, traditional communication protocols grapple with substantial challenges in meeting its burgeoning demands, including energy consumption, scalability, data management, and interference. In response to this, the integration of wireless power transfer and data transmission has emerged as a promising solution. This paper considers an energy harvesting (EH)-oriented data transmission scheme, where a set of users are charged by their own multi-antenna power beacon (PB) and subsequently transmits data to a base station (BS) using an irregular slotted aloha (IRSA) channel access protocol. We propose a closed-form expression to model energy consumption for the present scheme, employing average channel state information (A-CSI) beamforming in the wireless power channel. Subsequently, we employ the reinforcement learning (RL) methodology, wherein every user functions as an agent tasked with the goal of uncovering their most effective strategy for replicating transmissions. This strategy is devised while factoring in their energy constraints and the maximum number of packets they need to transmit. Our results underscore the viability of this solution, particularly when the PB can be strategically positioned to ensure a strong line-of- sight connection with the user, highlighting the potential benefits of optimal deployment.



## Index Terms

Wireless Powered Systems, Energy Harvesting, Power Beacon, Irregular Slotted Aloha, CSI.

## Acknowledgements

This work has been partially supported in Brazil by CAPES, Finance Code 001, CNPq (402378/2021-0, 305021/2021-4, 307226/2021-2). This work is funded by the European Union Project CENTRIC under Grant Agreement (GA 101096379), VERGE (GA 101096034) the project Infotech R2D2, the Research Council of Finland (former Academy of Finland) (GA 348515), and the Finnish Foundation for Technology Promotion. Views and opinions expressed are however those of the author(s) only and do not necessarily reflect those of the European Union or the European Commission (granting authority). Neither the European Union nor the granting authority can be held responsible for them.

### Afiliation

$^1$ Centre for Wireless Communication, University of Oulu, Finland 

$^2$ Federal University of Technology - Paraná, Brazil 

$^3$ Federal University of Santa Catarina, Brazil